apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: testapp
        image: docker.io/teslarez/flasktest:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: stage
          valueFrom:
            configMapKeyRef:
              name: testapp-config
              key: stage
        - name: name
          valueFrom:
            secretKeyRef:
              name: testapp-secret
              key: name